### ISSUE TITLE
RuntimeError: fft: ATen not compiled with MKL support

### ISSUE THREAD

**Issue by jainszhang** [kymatio/kymatio#278] opened 2018-12-21 07:16 UTC
when I run the examples , output like this:
Sx = scat(x)
  File "/Users/jains/anaconda2/envs/python36/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering2d/scattering2d.py", line 234, in __call__
  File "/Users/jains/anaconda2/envs/python36/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering2d/scattering2d.py", line 188, in forward
  File "/Users/jains/anaconda2/envs/python36/lib/python3.6/site-packages/kymatio-0.1.0.dev0-py3.6.egg/kymatio/scattering2d/backend/backend_torch.py", line 150, in fft
RuntimeError: fft: ATen not compiled with MKL support

May be the MKL version doesn't match?

**Comment by jainszhang** [comment] 2018-12-21 07:18
My os is Macos.

**Comment by eickenberg** [comment] 2018-12-21 08:55
Thanks for your report!

How did you install pytorch? The conda install from the website is the
easiest to get it to work because anaconda ships with mkl by default. If
you install numpy before pytorch, then you should have it.

In your file path I see it says "anaconda2" - is that because it's a
duplicate of another anaconda or because the install is the python 2.7-
based one, with py36 installed on top?

**Comment by eickenberg** [comment] 2018-12-21 13:16
Which example did you use actually?

The line that you are citing does not exist in the current codebase.

**Comment by janden** [comment] 2018-12-21 17:10
Could be related to this:

https://github.com/cornellius-gp/gpytorch/issues/194

Seems like doing the conda install or compiling pytorch from source may be the way to go.

**Comment by janden** [comment] 2019-01-03 16:55
@jainszhang Does this solve your problem?

**Comment by lostanlen** [comment] 2019-01-15 00:14
Hello @jainszhang, your problem probably goes up to an issue in PyTorch installation. We recommend installing with PyTorch and Kymatio through Anaconda, as noted in the link that @janden shared.

I am closing this because we cannot reproduce the issue, and you haven't replied in the past three weeks. Feel free to reopen this if the bug persists.

**Closed by lostanlen** 2019-01-15 00:14 UTC
Labels: bug

**Comment by jainszhang** [comment] 2019-01-15 08:01
> Hello @jainszhang, your problem probably goes up to an issue in PyTorch installation. We recommend installing with PyTorch and Kymatio through Anaconda, as noted in the link that @janden shared.
> 
> I am closing this because we cannot reproduce the issue, and you haven't replied in the past three weeks. Feel free to reopen this if the bug persists.

 I haven't read the mail in a long time, I am so sorry😫. I know my problem, you can close my question. And thank you very ... much.
