### ISSUE TITLE
Scattering Transform returns negative values 

### ISSUE THREAD

**Issue by GenoSmart** [kymatio/kymatio#719] opened 2021-04-13 09:22 UTC
Hello,
Is it makes sense I got negative values from the Scattering transform computation?
When I used Scattering Transform by MATLAB before, It never happened.

Thank U !

**Comment by lostanlen** [comment] 2021-04-13 11:53
Mathematically speaking, the scattering transform is nonnegative. However, Kymatio may occasionally return small negative values. Indeed, Kymatio doesn't guarantee that the low-pass filter phi is nonnegative. We build phi in the Fourier domain as a Gaussian, and the inverse Fourier transform of a Gaussian is also a Gaussian, so presumably phi should be positive both in the time domain and in the Fourier domain. But, in practice, phi turns out to be a truncated Gaussian in the Fourier domain, and thus a Gaussian convolved with sine cardinal in the time domain. This convolution with a sine cardinal profile causes some aliasing, leading to negative coefficients.

It imagine it could be possible to make the output more numerically accurate, at some cost in speed.

If you absolutely need nonnegative scattering coefficients (in NMF for example), consider passing `average=False` to Kymatio and taking care of averaging yourself.

**Comment by edouardoyallon** [comment] 2021-04-14 06:49
Would you please have an example to reproduce this? Thanks.

**Comment by lostanlen** [comment] 2021-04-14 08:47
@edouardoyallon 

```python
from kymatio.numpy import Scattering2D
import numpy as np

shape = (32, 32)
scattering = Scattering2D(J=2, shape=shape)
x = np.zeros(shape)
x[16, 16] = 1
sum(scattering(x)<0)
```


Result:
```
array([[22, 14, 28, 29,  1, 29, 27, 14],
       [15, 15, 15, 11,  1, 11, 15, 15],
       [28, 15,  3,  0,  0,  0,  3, 15],
       [29, 11,  0,  0,  0,  0,  0, 11],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [29, 11,  0,  0,  0,  0,  0, 11],
       [28, 15,  3,  0,  0,  0,  3, 15],
       [15, 15, 15, 11,  1, 11, 15, 15]])
```

**Comment by lostanlen** [comment] 2021-04-14 08:52
1-D example:

```python
from kymatio.numpy import Scattering1D

shape = (4096,)
scattering = Scattering1D(J=5, shape=shape)
x = np.zeros(shape)
x[2048] = 1
sum(scattering(x)<0)
```

Result:
```
array([0, 4, 2, 1, 1, 1, 4, 2, 1, 0, 1, 0, 0, 1, 1, 2, 1, 3, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 5, 1, 3, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0,
       1, 1, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 2, 1, 1, 0, 1, 4, 1, 2, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 3, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 2])
```

Note that increasing `J` seems to mitigate the problem. 
Set `J=4` in the 2-D example or `J=8` in the 1-D example and the output is nonnegative, as it should be.

**Comment by lostanlen** [comment] 2021-04-15 12:39
@GenoSmart Upon closer look, i think that there's no problem with the way our filter bank is set here. The fact that we perform the convolution with phi in the Fourier domain necessarily incurs some loss in floating-point precision.

```python
from kymatio.numpy import Scattering2D
shape = (32, 32)
scattering = Scattering2D(J=2, shape=shape)
x = np.zeros(shape)
x[16, 16] = 1
Sx = scattering(x).ravel()
idx = np.argsort(Sx)
plt.plot(np.log10(np.abs(Sx))[idx])
```

![signal-2021-04-12-203141](https://user-images.githubusercontent.com/3943142/114869981-eaff1280-9df7-11eb-935c-1a1164979935.jpeg)

All coefficients in the range [-1e-6, 1e-6] do not have a reliable amplitude (nor sign!) and should be considered numerically zero.

**Comment by lostanlen** [comment] 2021-04-15 12:43
@edouardoyallon @janden @eickenberg how about thresholding to zero all negative coefficients to avoid any possible confusion?

**Comment by OverLordGoldDragon** [comment] 2021-04-15 13:26
@lostanlen Not without incurring performance hit. Perhaps an FAQ page with "Why did I get negatives?"

**Comment by lostanlen** [comment] 2021-04-15 13:29
OK. For the time being we don't have an FAQ but we can still orient people towards this GH issue page.
Closing

**Closed by lostanlen** 2021-04-15 13:29 UTC

**Comment by OverLordGoldDragon** [comment] 2021-05-06 11:21
Looked into this; confirming it's purely FFT-derived float artifacts, all the negatives sum to `-1e-18`, which is below float64 epsilon. In most operations these will act identically as zeros, or actually turn into zeros:

```python
out = scattering(x)
print((out < 0).sum())
print((out - 1 + 1 < 0).sum())
```
```
>>> 87
>>> 0
```

**Comment by OverLordGoldDragon** [comment] 2021-05-06 11:30
Increasing `J` helps 'artificially' in that more output values end up within non-zero support range of the lowpass.
