### ISSUE TITLE
pip install kymatio fails on bare environment

### ISSUE THREAD

**Issue by MuawizChaudhary** [kymatio/kymatio#472] opened 2019-12-10 22:59 UTC
We should add torch to requriements.txt, according to @lostanlen .

**Comment by lostanlen** [comment] 2019-12-10 23:04
pytorch was removed by @edouardoyallon in https://github.com/kymatio/kymatio/pull/136
was this deliberate?

**Comment by lostanlen** [comment] 2019-12-10 23:04
Here is the commit tag
https://github.com/kymatio/kymatio/commit/ad98af79683b74b84a4575f36852f646e879eeff#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by edouardoyallon** [comment] 2019-12-10 23:10
The minimal requirement is numpy: maybe some users won't have torch or tf installed. @janden @eickenberg thoughts?

**Comment by lostanlen** [comment] 2019-12-10 23:11
Related: #419

**Comment by lostanlen** [comment] 2019-12-10 23:15
> The minimal requirement is numpy: maybe some users won't have torch or tf installed.

Exactly. The problem is that `import kymatio` fails on the current branch (v2) in a bare virtual environment (which does not include pytorch), because `scattering1d.py` imports torch:

See:
https://github.com/kymatio/kymatio/blob/kymatio-v2/kymatio/scattering1d/scattering1d.py#L7

**Comment by lostanlen** [comment] 2019-12-10 23:17
Ah, actually, this will be solved when #431 gets merged. It's just that we are in limbo between PRs on v2.

**Comment by lostanlen** [comment] 2019-12-10 23:28
Presumably the 2d numpy tests should catch this, though. Any explanation as to why they don't?

**Comment by lostanlen** [comment] 2019-12-11 14:32
Renaming to:  `pip install kymatio fails on bare environment`
It would be nice to test that this install works on pure numpy, once the pytorch dependency becomes completely optional.

**Comment by edouardoyallon** [comment] 2019-12-11 14:46
you can actually try it on the playground of pytest, that'd be awesome if you could do it!(as we'll finish the 1-3D branches)

**Comment by lostanlen** [comment] 2019-12-11 14:48
Cool! So can you confirm that, in Kymatio v0.2, it will be possible to run forward scattering on CPU with neither PyTorch nor TensorFlow installed?

**Comment by edouardoyallon** [comment] 2019-12-11 14:49
yes, this is the goal!!

**Comment by lostanlen** [comment] 2019-12-11 15:09
Nice!!
The way i would see it would be to modify the `travis_install.sh` so that it accepts more combinations of installation settings, via env variables:
* `IS_CONDA`: true/false
* `HAS_TENSORFLOW`: true/false
* `HAS_PYTORCH`: true/false

So eight in total. Times the number of Python versions (in our case, three).

Does that make sense?

If so, i can prepare a PR in this direction. Of course, we'd have to restrict to the case in which `HAS_TENSORFLOW` and `HAS_PYTORCH` are both `1` in `.travis.yml` to begin with, but then, once the other v02 PR get merged, we may consider adding the rest simply by updating the Trais YAML file.

**Comment by edouardoyallon** [comment] 2019-12-11 15:10
@janden @eickenberg

**Comment by janden** [comment] 2019-12-11 18:06
So `HAS_TENSORFLOW`, etc. will decide if it installs TF or not? I think that's a good idea. As I said in the Slack, I envision four testing environments:

- NP only
- NP+Torch
- NP+Torch+skcuda/cupy
- NP+TF

I don't think there's a need to test with both Torch and TF simultaneously.

Other than changing the testing configuration, we also need to make sure we're not importing Torch anywhere we shouldn't. This includes, crucially, the tests suites, since these contain the test data stored as Torch files. We will have to recreate these in NP and save them that way. This will also allow us to reorder the coefficients in the correct (new) order, allowing us to remove the `reorder_interleaved_coefficients` function.

**Comment by edouardoyallon** [comment] 2019-12-11 18:08
> Other than changing the testing configuration, we also need to make sure we're not importing Torch anywhere we shouldn't. This includes, crucially, the tests suites, since these contain the test data stored as Torch files. We will have to recreate these in NP and save them that way. This will also allow us to reorder the coefficients in the correct (new) order, allowing us to remove the `reorder_interleaved_coefficients` function.

Please see: #419

**Comment by lostanlen** [comment] 2019-12-11 23:58
@janden yes, the overarching goal is to only "pay for what we use", i.e., depend on a minimal number of libraries. But the more urgent goal is to have a pip distribution which runs out of the box. Currently, that is not the case on `kymatio-v2` branch.
I would recommend that we keep this issue open for the question of having a self-contained  `setup.py`, and turning to #419 for the more ambitious goal of being able to run tests in pure numpy.

**Comment by janden** [comment] 2019-12-12 20:15
> more ambitious goal of being able to run tests in pure numpy.

It's a couple of lines of code. I don't like the idea of having a formal list of requirements (either in `requirements.txt` or `setup.py`), but then having the most basic tests fail unless additional dependencies are satisfied.

**Comment by lostanlen** [comment] 2019-12-12 20:22
I don't understand what you just wrote.

**Comment by janden** [comment] 2019-12-12 20:24
Having a pip distribution which runs out of the box means having tests that run out of the box, as well. They're not separate issues.

**Comment by lostanlen** [comment] 2019-12-13 00:13
Oh, i see what you mean. I think you and me agree here. 

Our `travis_install.sh` is quite complex, as it involves installing pytorch manually before calling `python setup.py develop` : https://github.com/kymatio/kymatio/blob/master/tools/travis_install.sh

Whereas our `README.md` (on the v2 branch) only mentions `pip install kymatio`, glossing our the fact that the backend library needs to be installed ahead of time.

So there are several ways to tackle this: make the doc match the distribution or vice-versa.

**Comment by edouardoyallon** [comment] 2020-01-24 03:52
where are we?

**Comment by lostanlen** [comment] 2020-01-25 13:39
let's discuss this issue today in person

**Comment by edouardoyallon** [comment] 2020-01-27 07:21
It seems pretty clear to our discussion the last days that: an user willing to develop for the software should install the whole set of packages we have, yet the option to install `torch` or other is optional, yet shouldn't fail.

Am i correct?

**Comment by lostanlen** [comment] 2020-01-27 13:25
@edouardoyallon yes you are correct, but as of today (branch 0.2.X), it seems impossible to use kymatio without torch.

Installation works and import also works but the `Scattering2d` constructor raises an error

Full error log attached:
[install_error.txt](https://github.com/kymatio/kymatio/files/4117285/install_error.txt)

**Comment by edouardoyallon** [comment] 2020-01-27 13:34
Right, I think there is an abrupt message

>  DeprecationWarning: Torch frontend is currently the default, but NumPy will become the default in the next version.
>   warnings.warn("Torch frontend is currently the default, but NumPy will become the default in the next"

That we could turn into a `try import torch finalize import numpy`.. but I(m fine with it. Thoughts?

**Comment by lostanlen** [comment] 2020-01-28 17:42
@edouard ah, i see what you mean. so torch is still required as of 0.2.X ? in this case, it needs to appear in requirements.
i'm unclear about what our versioning/packaging policy is here.

**Comment by edouardoyallon** [comment] 2020-02-19 17:30
@janden What should we do about this one? A decision must be taken.

**Comment by janden** [comment] 2020-02-26 03:59
So I think this is now resolved. From what I understand, torch should no longer be a requirement. I just tested this on a bare environment (i.e., just running `pip install -r requirements.txt`) and it seems to work:
```
from kymatio.numpy import Scattering2D
S = Scattering2D(J=2, shape=(32, 32))
x = np.random.randn(32, 32)
Sx = S(x)
```

Of course, doing
```
from kymatio import Scattering2D
S = Scattering2D(J=2, shape=(32, 32))
```
fails, since torch is still the default frontend. However,
```
S = Scattering2D(J=2, shape=(32, 32), frontend='numpy')
```
works as expected.

**Comment by edouardoyallon** [comment] 2020-02-26 19:41
Awesome.

**Closed by edouardoyallon** 2020-02-26 19:41 UTC
Labels: good first issue

**Comment by lostanlen** [comment] 2020-02-26 20:43
Amazing !!!!
