### ISSUE TITLE
Ill-conditioning in `scattering3d_qm7.py`

### ISSUE THREAD

**Issue by janden** [kymatio/kymatio#309] opened 2019-01-17 15:10 UTC
When running this, I get
```
...
Ridge regression, alpha: 1.0, MAE: 5.897314548492432, RMSE: 8.19788932800293
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.719067e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.847256e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.704315e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.990118e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.824673e-08
  overwrite_a=True).T
...
```
Seems like `alpha = 1.0` is a bad idea? Why do we have this in here?

**Comment by eickenberg** [comment] 2019-01-17 17:58
Hm so in terms of accuracy `alpha=1` is certainly a bad idea since it introduces too much unnecessary bias. I'm surprised it would do badly on the Ridge regression if the lower penalties, e.g. 1e-5 don't (it should be them that emit this error -- is the above error related to alpha=1 or could it be related to the other ones?).

Apart from that, giving the Ridge object a different solver to use should also fix this

**Comment by janden** [comment] 2019-01-17 18:19
>  is the above error related to alpha=1 or could it be related to the other ones?

Not sure, actually. Here's the full output:
```
Computing solid harmonic scattering coefficients of 7165 molecules of QM7 database on GPU
sigma: 2.0, L: 3, J: 2, integral powers: [0.5, 1.0, 2.0, 3.0]
Ridge regression, alpha: 1.0, MAE: 5.897314548492432, RMSE: 8.19788932800293
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.719067e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.847256e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.704315e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.990118e-08
  overwrite_a=True).T
/mnt/xfs1/home/janden/local/anaconda3/envs/kymatio_cuda90/lib/python3.7/site-packages/sklearn/linear_model/ridge.py:125: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number1.824673e-08
  overwrite_a=True).T
Ridge regression, alpha: 0.1, MAE: 4.911195755004883, RMSE: 6.90034818649292
Ridge regression, alpha: 0.01, MAE: 4.034888744354248, RMSE: 5.778854846954346
Ridge regression, alpha: 0.001, MAE: 3.3446338176727295, RMSE: 4.842739105224609
Ridge regression, alpha: 0.0001, MAE: 2.9704883098602295, RMSE: 4.403475284576416
Ridge regression, alpha: 1e-05, MAE: 2.801150321960449, RMSE: 4.204596996307373
Ridge regression, alpha: 1e-06, MAE: 2.742659568786621, RMSE: 4.122145175933838
Ridge regression, alpha: 1e-07, MAE: 2.751904249191284, RMSE: 4.104255199432373
Ridge regression, alpha: 1e-08, MAE: 2.9777421951293945, RMSE: 4.275634288787842
Ridge regression, alpha: 1e-09, MAE: 3.2388601303100586, RMSE: 4.525323390960693
```

**Comment by MuawizChaudhary** [comment] 2020-01-27 01:59
Is this still a problem? @janden @eickenberg

**Comment by MuawizChaudhary** [comment] 2020-01-27 01:59
Is this still a problem? @janden @eickenberg

**Comment by edouardoyallon** [comment] 2020-02-19 07:25
This was merged and fixed!

**Closed by edouardoyallon** 2020-02-19 07:25 UTC
Labels: 3D
